name: "Push"

on:
  push:
    branches: ['main']

jobs:
  check:
    name: 'cargo check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
  test:
    name: 'test'
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Smoke test'
        run: ./test.sh