name: "Push"

on:
  push:
    branches: ['main']

jobs:
  check:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo build --release
      - run: ./test.sh